package com.tweetapp.bean;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

/**
 * @author Pravin Richard
 *
 */
@DynamoDBTable(tableName = "users")
public class Users {

	@Override
	public String toString() {
		return "Users [id=" + id + ", firstName=" + firstName + ", lastName=" + lastName + ", email=" + email
				+ ", loginId=" + loginId + ", password=" + password + ", confirmPassword=" + confirmPassword
				+ ", contactNumber=" + contactNumber + ", isLogin=" + isLogin + "]";
	}

	private String id;

	private String firstName;

	private String lastName;

	private String email;

	private String loginId;

	private String password;

	private String confirmPassword;

	private long contactNumber;

	private boolean isLogin = false;

	/**
	 * @return id
	 */
	
	@DynamoDBHashKey(attributeName ="id")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * @return firstName
	 */
	@DynamoDBAttribute(attributeName ="firstName")	
	public String getFirstName() {
		return firstName;
	}

	/**
	 * @param firstName the firstName to set
	 */
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	/**
	 * @return lastName
	 */
	@DynamoDBAttribute(attributeName ="lastName")
	public String getLastName() {
		return lastName;
	}

	/**
	 * @param lastName the lastName to set
	 */
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	/**
	 * @return email
	 */
	@DynamoDBAttribute(attributeName ="email")
	public String getEmail() {
		return email;
	}

	/**
	 * @param email the email to set
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * @return loginId
	 */
	@DynamoDBAttribute(attributeName ="loginId")
	public String getLoginId() {
		return loginId;
	}

	/**
	 * @param loginId the loginId to set
	 */
	public void setLoginId(String loginId) {
		this.loginId = loginId;
	}

	/**
	 * @return password
	 */
	@DynamoDBAttribute(attributeName ="password")
	public String getPassword() {
		return password;
	}

	/**
	 * @param password the password to set
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * @return confirmPassword
	 */
	@DynamoDBAttribute(attributeName ="confirmPassword")
	public String getConfirmPassword() {
		return confirmPassword;
	}

	/**
	 * @param confirmPassword the confirmPassword to set
	 */
	public void setConfirmPassword(String confirmPassword) {
		this.confirmPassword = confirmPassword;
	}

	/**
	 * @return contactNumber
	 */
	@DynamoDBAttribute(attributeName ="contactNumber")
	public long getContactNumber() {
		return contactNumber;
	}

	/**
	 * @param contactNumber the contactNumber to set
	 */
	public void setContactNumber(long contactNumber) {
		this.contactNumber = contactNumber;
	}

	/**
	 * @return isLogin
	 */
	@DynamoDBAttribute(attributeName ="isLogin")
	public boolean isLogin() {
		return isLogin;
	}

	/**
	 * @param isLogin the isLogin to set
	 */
	public void setLogin(boolean isLogin) {
		this.isLogin = isLogin;
	}

}
